### ISSUE TITLE
Maverick Fühler anschließen

### ISSUE THREAD

**Issue by rgruebel** [zaphi/Grilloino2000#1]
Hallo, 
ich will auch einen WLAN-Thermometer bauen und schaue mir bei deinem Projekt einiges ab. In einem simplen Aufbau versuche ich im Moment sinnvolle Werte von meinen Fühlern auszulesen aber komme leider auf keinen grünen Zweig. Kannst du vlt einen Blick auf meine Verkabelung werfen und hast eine Idee was da nicht passt?
![20190522_220225](https://user-images.githubusercontent.com/1482159/58206057-3bd76080-7ce0-11e9-96ec-021a522f970a.jpg)

**Comment by zaphi** [comment]
Hi, den Maverick Fühler gibt es auch mit einem widerstand von 1000Ohm das musst du in der probe.h dementsprechend anpassen. sonst zeigt er immer 0 Grad an.
